export interface StickerDef {
  file: string
  label: string
  category: string
}

export const STICKER_CATEGORIES = ['All', 'Kawaii', 'Study', 'Mood', 'Bodies', 'Food', 'Extras'] as const

export const STICKERS: StickerDef[] = [
  { file: 'sticker_01_bunny_heart.png', label: 'Bunny Heart', category: 'Kawaii' },
  { file: 'sticker_02_bear_boba.png', label: 'Bear Boba', category: 'Kawaii' },
  { file: 'sticker_03_cat_toast.png', label: 'Cat Toast', category: 'Kawaii' },
  { file: 'sticker_04_puppy_cry.png', label: 'Puppy Cry', category: 'Kawaii' },
  { file: 'sticker_05_hamster_strawberry.png', label: 'Hamster Strawberry', category: 'Kawaii' },
  { file: 'sticker_06_chick_bow.png', label: 'Chick Bow', category: 'Kawaii' },
  { file: 'sticker_07_penguin_book.png', label: 'Penguin Book', category: 'Kawaii' },
  { file: 'sticker_08_fox_cloud.png', label: 'Fox Cloud', category: 'Kawaii' },
  { file: 'sticker_09_capybara_bath.png', label: 'Capybara Bath', category: 'Kawaii' },
  { file: 'sticker_10_seal_love.png', label: 'Seal Love', category: 'Kawaii' },
  { file: 'sticker_12_koala_laptop.png', label: 'Koala Laptop', category: 'Kawaii' },
  { file: 'sticker_13_bunny_angry.png', label: 'Bunny Angry', category: 'Kawaii' },
  { file: 'sticker_16_bunny_carrot.png', label: 'Bunny Carrot', category: 'Kawaii' },
  { file: 'sticker_17_frog_umbrella.png', label: 'Frog Umbrella', category: 'Kawaii' },
  { file: 'sticker_18_corgi_heart.png', label: 'Corgi Heart', category: 'Kawaii' },
  { file: 'sticker_19_otters_holding.png', label: 'Otters Holding', category: 'Kawaii' },
  { file: 'sticker_20_duck_float.png', label: 'Duck Float', category: 'Kawaii' },
  { file: 'sticker_21_mochi_cats.png', label: 'Mochi Cats', category: 'Kawaii' },
  { file: 'sticker_22_bear_shy.png', label: 'Bear Shy', category: 'Kawaii' },
  { file: 'sticker_23_star_moon.png', label: 'Star Moon', category: 'Kawaii' },
  { file: 'sticker_24_bunny_gaming.png', label: 'Bunny Gaming', category: 'Kawaii' },
  { file: 'sticker_25_cat_heart_hands.png', label: 'Cat Heart', category: 'Kawaii' },
  { file: 'sticker_26_puppy_donut.png', label: 'Puppy Donut', category: 'Kawaii' },
  { file: 'sticker_27_pig_dance.png', label: 'Pig Dance', category: 'Kawaii' },
  { file: 'sticker_28_bear_letter.png', label: 'Bear Letter', category: 'Kawaii' },
  { file: 'sticker_29_cat_typing.png', label: 'Cat Typing', category: 'Kawaii' },
  { file: 'sticker_30_bunny_flowers.png', label: 'Bunny Flowers', category: 'Kawaii' },
  { file: 'sticker_31_seal_icecream.png', label: 'Seal Icecream', category: 'Kawaii' },
  { file: 'sticker_32_hamster_coffee.png', label: 'Hamster Coffee', category: 'Kawaii' },
  { file: 'sticker_33_ghost_bow.png', label: 'Ghost Bow', category: 'Kawaii' },
  { file: 'sticker_34_cloud_cry.png', label: 'Cloud Cry', category: 'Kawaii' },
  { file: 'sticker_35_bear_pajama.png', label: 'Bear Pajama', category: 'Kawaii' },
  { file: 'rabbit_book_pose.png', label: 'Reading Bunny', category: 'Study' },
  { file: 'rabbit_laptop_1.png', label: 'Laptop Bunny', category: 'Study' },
  { file: 'coding.png', label: 'Coding', category: 'Study' },
  { file: 'reading.png', label: 'Reading', category: 'Study' },
  { file: 'exam.png', label: 'Exam', category: 'Study' },
  { file: 'idea.png', label: 'Idea', category: 'Study' },
  { file: 'drawing.png', label: 'Drawing', category: 'Study' },
  { file: 'meeting.png', label: 'Meeting', category: 'Study' },
  { file: 'todo.png', label: 'Todo', category: 'Study' },
  { file: 'calendar.png', label: 'Calendar', category: 'Study' },
  { file: 'timer.png', label: 'Timer', category: 'Study' },
  { file: 'graduation.png', label: 'Graduation', category: 'Study' },
  { file: 'happy.png', label: 'Happy', category: 'Mood' },
  { file: 'excited.png', label: 'Excited', category: 'Mood' },
  { file: 'sad.png', label: 'Sad', category: 'Mood' },
  { file: 'confused.png', label: 'Confused', category: 'Mood' },
  { file: 'hi.png', label: 'Hi', category: 'Mood' },
  { file: 'star.png', label: 'Star', category: 'Mood' },
  { file: 'gift.png', label: 'Gift', category: 'Mood' },
  { file: 'random_sleep.png', label: 'Sleep', category: 'Mood' },
  { file: 'rabbit_sleepy.png', label: 'Sleepy Bunny', category: 'Mood' },
  { file: 'coffee.png', label: 'Coffee', category: 'Food' },
  { file: 'ramen.png', label: 'Ramen', category: 'Food' },
  { file: 'cake.png', label: 'Cake', category: 'Food' },
  { file: 'random_cake.png', label: 'Random Cake', category: 'Food' },
  { file: 'water.png', label: 'Water', category: 'Food' },
  { file: 'blanket.png', label: 'Blanket', category: 'Extras' },
  { file: 'cleaning.png', label: 'Cleaning', category: 'Extras' },
  { file: 'gaming.png', label: 'Gaming', category: 'Extras' },
  { file: 'guitar.png', label: 'Guitar', category: 'Extras' },
  { file: 'gym.png', label: 'Gym', category: 'Extras' },
  { file: 'movie.png', label: 'Movie', category: 'Extras' },
  { file: 'shopping.png', label: 'Shopping', category: 'Extras' },
  { file: 'travel.png', label: 'Travel', category: 'Extras' },
  { file: 'random_plant.png', label: 'Plant', category: 'Extras' },
  { file: 'birthday.png', label: 'Birthday', category: 'Extras' },
  { file: 'organ_brain.png', label: 'Brain', category: 'Bodies' },
  { file: 'organ_heart.png', label: 'Heart', category: 'Bodies' },
  { file: 'organ_lungs.png', label: 'Lungs', category: 'Bodies' },
  { file: 'organ_stomach.png', label: 'Stomach', category: 'Bodies' },
  { file: 'organ_liver.png', label: 'Liver', category: 'Bodies' },
  { file: 'organ_kidneys.png', label: 'Kidneys', category: 'Bodies' },
  { file: 'organ_muscle.png', label: 'Muscle', category: 'Bodies' },
  { file: 'organ_bone.png', label: 'Bone', category: 'Bodies' },
  { file: 'organ_dna.png', label: 'DNA', category: 'Bodies' },
  { file: 'organ_neuron.png', label: 'Neuron', category: 'Bodies' },
  { file: 'organ_rbc.png', label: 'Red Blood Cell', category: 'Bodies' },
  { file: 'organ_wbc.png', label: 'White Blood Cell', category: 'Bodies' },
  { file: 'organ_spleen.png', label: 'Spleen', category: 'Bodies' },
  { file: 'organ_pancreas.png', label: 'Pancreas', category: 'Bodies' },
  { file: 'organ_bladder.png', label: 'Bladder', category: 'Bodies' },
  { file: 'organ_large_intestine.png', label: 'Large Intestine', category: 'Bodies' },
  { file: 'organ_small_intestine.png', label: 'Small Intestine', category: 'Bodies' },
  { file: 'organ_uterus.png', label: 'Uterus', category: 'Bodies' },
]
