import type { MusicPreset } from './types'

// The Library Realm focus presets, in the order they appear in the playlist
// selector. Every track is royalty-free and legally playable on the site:
//
//   • Local files (public/audio/*.mp3) — self-hosted rain / birds recordings.
//   • Synthesized noise (no asset) — brown noise & deep focus, made in-browser.
//   • Kevin MacLeod (incompetech.com) — CC BY 3.0. Attribution: "Kevin MacLeod
//     (incompetech.com) Licensed under Creative Commons: By Attribution 3.0".
//     Shown next to each track below (short "Kevin MacLeod" credit in the UI).
//   • Craig Smith / USC Optical Sound Effects Library (archive.org) — CC0 1.0.
//
// All remote URLs were verified reachable (HTTP 200) when this list was written.
// Artwork needs NO image files: each tile is a warm CSS gradient (`tint`) with
// the `glyph` on top.

export const MUSIC_PRESETS: MusicPreset[] = [
  // ── Curated cozy focus tracks ─────────────────────────────────────────
  {
    id: 'lofi',
    name: 'Lofi Focus',
    subtitle: 'Mellow chill loop · Kevin MacLeod',
    glyph: '🎧',
    tint: ['#7a4a26', '#a9703f'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Chill%20Wave.mp3' },
    available: true,
  },
  {
    id: 'piano',
    name: 'Piano Study',
    subtitle: 'Soft solo piano · Kevin MacLeod',
    glyph: '🎹',
    tint: ['#5c3518', '#8a5a32'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Meditation%20Impromptu%2002.mp3' },
    available: true,
  },
  {
    id: 'classical',
    name: 'Classical Concentration',
    subtitle: 'Calm, focused piano · Kevin MacLeod',
    glyph: '🎻',
    tint: ['#6b4423', '#b07d45'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Friday%20Morning.mp3' },
    available: true,
  },
  {
    id: 'ambient-drift',
    name: 'Ambient Drift',
    subtitle: 'Slow sonorous pads · Kevin MacLeod',
    glyph: '🌫️',
    tint: ['#35455a', '#5a7285'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Ambiment.mp3' },
    available: true,
  },
  {
    id: 'peace-of-mind',
    name: 'Peace of Mind',
    subtitle: 'Deep calm ambient · Kevin MacLeod',
    glyph: '🕊️',
    tint: ['#3a3f4a', '#5f6b7a'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Peace%20of%20Mind.mp3' },
    available: true,
  },
  {
    id: 'almost-in-f',
    name: 'Almost in F',
    subtitle: 'Long-form ambient · Kevin MacLeod',
    glyph: '🌌',
    tint: ['#2f3b47', '#50697a'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Almost%20in%20F.mp3' },
    available: true,
  },
  {
    id: 'drone-d',
    name: 'Drone in D',
    subtitle: 'Meditative drone · Kevin MacLeod',
    glyph: '🧘',
    tint: ['#3a3327', '#6b5a3f'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Drone%20in%20D.mp3' },
    available: true,
  },
  {
    id: 'organic-meditations',
    name: 'Organic Meditations',
    subtitle: 'Warm ambient tones · Kevin MacLeod',
    glyph: '🌿',
    tint: ['#2f4a3a', '#4f7a5f'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Organic%20Meditations%20Three.mp3' },
    available: true,
  },
  {
    id: 'perspectives',
    name: 'Perspectives',
    subtitle: 'Shifting ambient layers · Kevin MacLeod',
    glyph: '🔭',
    tint: ['#33283f', '#5a4a6b'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Perspectives.mp3' },
    available: true,
  },
  {
    id: 'garden-music',
    name: 'Garden Music',
    subtitle: 'Relaxing outdoor ambient · Kevin MacLeod',
    glyph: '🌸',
    tint: ['#4a3a2a', '#7a6b4a'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Garden%20Music.mp3' },
    available: true,
  },
  {
    id: 'healing',
    name: 'Healing',
    subtitle: 'Gentle restorative pads · Kevin MacLeod',
    glyph: '💚',
    tint: ['#2f4650', '#4f6b7a'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Healing.mp3' },
    available: true,
  },
  {
    id: 'heartwarming',
    name: 'Heartwarming',
    subtitle: 'Tender soft piano · Kevin MacLeod',
    glyph: '🤍',
    tint: ['#4a2f2f', '#7a5050'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Heartwarming.mp3' },
    available: true,
  },
  {
    id: 'comfortable-mystery',
    name: 'Comfortable Mystery',
    subtitle: 'Soft curious ambient · Kevin MacLeod',
    glyph: '🕯️',
    tint: ['#3f3328', '#6b5a4a'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Comfortable%20Mystery.mp3' },
    available: true,
  },
  {
    id: 'dreamy-flashback',
    name: 'Dreamy Flashback',
    subtitle: 'Hazy dreamy pads · Kevin MacLeod',
    glyph: '☁️',
    tint: ['#333a4a', '#5a6b82'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Dreamy%20Flashback.mp3' },
    available: true,
  },
  {
    id: 'mystic-force',
    name: 'Mystic Force',
    subtitle: 'Mysterious calm ambient · Kevin MacLeod',
    glyph: '✨',
    tint: ['#3f2f45', '#6b4a7a'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Mystic%20Force.mp3' },
    available: true,
  },
  {
    id: 'meditation-1',
    name: 'Meditation Impromptu',
    subtitle: 'Classical-style piano · Kevin MacLeod',
    glyph: '🎵',
    tint: ['#5a3a1f', '#8a6b3f'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Meditation%20Impromptu%2001.mp3' },
    available: true,
  },
  {
    id: 'touching-moments',
    name: 'Touching Moments',
    subtitle: 'Emotive soft piano · Kevin MacLeod',
    glyph: '💫',
    tint: ['#4a2f1f', '#7a5a3a'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Touching%20Moments%20Five%20-%20Circle.mp3' },
    available: true,
  },
  {
    id: 'lotus',
    name: 'Lotus',
    subtitle: 'Serene meditative flow · Kevin MacLeod',
    glyph: '🪷',
    tint: ['#3a3f4a', '#5f6b82'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Lotus.mp3' },
    available: true,
  },
  {
    id: 'moonlight-hall',
    name: 'Moonlight Hall',
    subtitle: 'Hushed late-night ambient · Kevin MacLeod',
    glyph: '🌙',
    tint: ['#2a2540', '#4a4368'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Moonlight%20Hall.mp3' },
    available: true,
  },
  {
    id: 'windswept',
    name: 'Windswept',
    subtitle: 'Airy open ambient · Kevin MacLeod',
    glyph: '🍃',
    tint: ['#33423a', '#5f7a6a'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Windswept.mp3' },
    available: true,
  },
  {
    id: 'at-rest',
    name: 'At Rest',
    subtitle: 'Quiet settling soundtrack · Kevin MacLeod',
    glyph: '🕰️',
    tint: ['#2c2c3f', '#4a4a63'],
    source: { kind: 'loop', url: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/At%20Rest.mp3' },
    available: true,
  },
  {
    id: 'storm-rain',
    name: 'Storm Rain',
    subtitle: 'Heavy rain & wind · CC0 archive.org',
    glyph: '🌦️',
    tint: ['#26303a', '#43556a'],
    source: { kind: 'loop', url: 'https://archive.org/download/Red_Library_Nature_Rain/R10-04-Heavy%20Rain%20and%20Wind.mp3' },
    available: true,
  },

  // ── Synth noise (no asset needed) ─────────────────────────────────────
  {
    id: 'brown',
    name: 'Brown Noise',
    subtitle: 'Steady, warm static',
    glyph: '🟤',
    tint: ['#4a2f18', '#7a4a26'],
    source: { kind: 'noise', variant: 'brown' },
    available: true,
  },

  // ── Local looping recordings (public/audio) ───────────────────────────
  {
    id: 'rain',
    name: 'Rain Ambience',
    subtitle: 'Gentle rainfall',
    glyph: '🌧️',
    tint: ['#3f4a52', '#6b7a82'],
    source: { kind: 'loop', url: '/audio/rain.mp3' },
    available: true,
  },
  {
    id: 'rain-interior',
    name: 'Rain · Interior',
    subtitle: 'Rain against the windows',
    glyph: '🪟',
    tint: ['#36474f', '#5f7682'],
    source: { kind: 'loop', url: '/audio/rain-interior.mp3' },
    available: true,
  },
  {
    id: 'rain-exterior',
    name: 'Rain · Exterior',
    subtitle: 'Storm over the realm',
    glyph: '🌧️',
    tint: ['#2f3b47', '#50697a'],
    source: { kind: 'loop', url: '/audio/rain-exterior.mp3' },
    available: true,
  },
  {
    id: 'rain-thunder',
    name: 'Rain & Thunder',
    subtitle: 'Distant rolling thunder',
    glyph: '⛈️',
    tint: ['#2b333d', '#4a5a68'],
    source: { kind: 'loop', url: '/audio/rain-rumble.mp3' },
    available: true,
  },
  {
    id: 'forest',
    name: 'Forest & Birds',
    subtitle: 'Birds & rustling leaves',
    glyph: '🌲',
    tint: ['#2f4a2f', '#5a7a4a'],
    source: { kind: 'loop', url: '/audio/birds.mp3' },
    available: true,
  },
  {
    id: 'night-library',
    name: 'Night Library',
    subtitle: 'Hushed late-night hall',
    glyph: '🌙',
    tint: ['#2a2540', '#4a4368'],
    source: { kind: 'loop', url: '/audio/music-ambient.mp3' },
    available: true,
  },
  {
    id: 'deep',
    name: 'Deep Focus',
    subtitle: 'Low, enveloping hum',
    glyph: '🧠',
    tint: ['#3a2a17', '#6b4a2a'],
    source: { kind: 'noise', variant: 'deep' },
    available: true,
  },

  // ── Jamendo stream (free, ad-free, no account) ──────────────────────────
  // CC-licensed Jamendo tracks mirrored on archive.org with stable direct MP3
  // URLs. These play end-to-end (no loop) and auto-advance to the next track
  // when one finishes — the playlist "flows". Every URL was verified (HTTP 200)
  // when this list was written.
  {
    id: 'jam-lofi-study',
    name: 'Lofi hip hop study',
    subtitle: 'Emil · Jamendo',
    glyph: '🎧',
    tint: ['#4a3a55', '#7a5a8a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-476651/01-1931249-Emil-Lofi%20hip%20hop%20study.mp3' },
    available: true,
  },
  {
    id: 'jam-shuttle',
    name: 'Shuttle',
    subtitle: 'Slxt Sync · Jamendo',
    glyph: '🎧',
    tint: ['#4a3a55', '#7a5a8a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-612992/01-2274653-Slxt%20Sync-Shuttle.mp3' },
    available: true,
  },
  {
    id: 'jam-green-background',
    name: 'green background',
    subtitle: 'Slxt Sync · Jamendo',
    glyph: '🎧',
    tint: ['#3f4a52', '#6b7a82'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-612992/02-2274654-Slxt%20Sync-green%20background.mp3' },
    available: true,
  },
  {
    id: 'jam-full-moon',
    name: 'full moon',
    subtitle: 'Slxt Sync · Jamendo',
    glyph: '🌙',
    tint: ['#3f4a52', '#6b7a82'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-612992/03-2274652-Slxt%20Sync-full%20moon.mp3' },
    available: true,
  },
  {
    id: 'jam-elevation',
    name: 'elevation',
    subtitle: 'Slxt Sync · Jamendo',
    glyph: '🎧',
    tint: ['#3f4a52', '#6b7a82'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-612992/04-2274651-Slxt%20Sync-elevation.mp3' },
    available: true,
  },
  {
    id: 'jam-chill-carpet',
    name: 'chill carpet',
    subtitle: 'Slxt Sync · Jamendo',
    glyph: '🎧',
    tint: ['#3f4a52', '#6b7a82'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-612992/05-2274650-Slxt%20Sync-chill%20carpet.mp3' },
    available: true,
  },
  {
    id: 'jam-meant-to-be',
    name: 'Meant to Be',
    subtitle: 'Rob Costlow · Jamendo',
    glyph: '🎹',
    tint: ['#3a3f55', '#5a6a8a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-000888/01.mp3' },
    available: true,
  },
  {
    id: 'jam-reflections',
    name: 'Reflections',
    subtitle: 'Rob Costlow · Jamendo',
    glyph: '🎹',
    tint: ['#3a3f55', '#5a6a8a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-000888/02.mp3' },
    available: true,
  },
  {
    id: 'jam-semester-days',
    name: 'Semester Days',
    subtitle: 'Rob Costlow · Jamendo',
    glyph: '🎹',
    tint: ['#3a3f55', '#5a6a8a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-000888/03.mp3' },
    available: true,
  },
  {
    id: 'jam-tulip-trees',
    name: 'Tulip Trees',
    subtitle: 'Rob Costlow · Jamendo',
    glyph: '🎹',
    tint: ['#3a3f55', '#5a6a8a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-000888/07.mp3' },
    available: true,
  },
  {
    id: 'jam-twilight',
    name: 'Twilight',
    subtitle: 'Rob Costlow · Jamendo',
    glyph: '🎹',
    tint: ['#3a3f55', '#5a6a8a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-000888/10.mp3' },
    available: true,
  },
  {
    id: 'jam-intro',
    name: 'Intro',
    subtitle: 'zero-project · Jamendo',
    glyph: '🌌',
    tint: ['#2a3f4a', '#4a6a7a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-055681/01.mp3' },
    available: true,
  },
  {
    id: 'jam-high-hopes',
    name: 'High hopes',
    subtitle: 'zero-project · Jamendo',
    glyph: '🌌',
    tint: ['#2a3f4a', '#4a6a7a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-055681/02.mp3' },
    available: true,
  },
  {
    id: 'jam-twilight-poem',
    name: 'Twilight poem',
    subtitle: 'zero-project · Jamendo',
    glyph: '🌌',
    tint: ['#2a3f4a', '#4a6a7a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-055681/03.mp3' },
    available: true,
  },
  {
    id: 'jam-breath-of-freedom',
    name: 'Breath of freedom',
    subtitle: 'zero-project · Jamendo',
    glyph: '🌌',
    tint: ['#2a3f4a', '#4a6a7a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-055681/04.mp3' },
    available: true,
  },
  {
    id: 'jam-silent-force',
    name: 'The silent force',
    subtitle: 'zero-project · Jamendo',
    glyph: '🌌',
    tint: ['#2a3f4a', '#4a6a7a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-055681/05.mp3' },
    available: true,
  },
  {
    id: 'jam-dawn-of-a-new-era',
    name: 'Dawn of a new era',
    subtitle: 'zero-project · Jamendo',
    glyph: '🌅',
    tint: ['#4a3a2a', '#7a5a3a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-055681/07.mp3' },
    available: true,
  },
  {
    id: 'jam-path-of-loneliness',
    name: 'Path of loneliness',
    subtitle: 'zero-project · Jamendo',
    glyph: '🌌',
    tint: ['#2a3f4a', '#4a6a7a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-055681/08.mp3' },
    available: true,
  },
  {
    id: 'jam-neverending-dream',
    name: 'Neverending dream',
    subtitle: 'zero-project · Jamendo',
    glyph: '🌌',
    tint: ['#2a3f4a', '#4a6a7a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-055681/09.mp3' },
    available: true,
  },
  {
    id: 'jam-dreaming-ambient',
    name: 'Dreaming Ambient',
    subtitle: 'Plastic3 · Jamendo',
    glyph: '🌌',
    tint: ['#2a3f4a', '#4a6a7a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-103271/01.mp3' },
    available: true,
  },
  {
    id: 'jam-chill-relax-piano',
    name: 'Chill Relax Piano',
    subtitle: 'Plastic3 · Jamendo',
    glyph: '🎹',
    tint: ['#3a3f55', '#5a6a8a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-103271/04.mp3' },
    available: true,
  },
  {
    id: 'jam-soft-calm-chillout',
    name: 'Soft Calm Chillout',
    subtitle: 'Plastic3 · Jamendo',
    glyph: '🌌',
    tint: ['#2a3f4a', '#4a6a7a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-103271/06.mp3' },
    available: true,
  },
  {
    id: 'jam-ambient-chill-soft',
    name: 'Ambient Chill Soft',
    subtitle: 'Plastic3 · Jamendo',
    glyph: '🌌',
    tint: ['#2a3f4a', '#4a6a7a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-103271/10.mp3' },
    available: true,
  },
  {
    id: 'jam-chameleon',
    name: 'Chameleon',
    subtitle: 'Jumbo Jazz · Jamendo',
    glyph: '🎷',
    tint: ['#4a3a2a', '#7a5a3a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-068493/01.mp3' },
    available: true,
  },
  {
    id: 'jam-take-the-a-train',
    name: "Take The 'A' Train",
    subtitle: 'Jumbo Jazz · Jamendo',
    glyph: '🎷',
    tint: ['#4a3a2a', '#7a5a3a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-068493/02.mp3' },
    available: true,
  },
  {
    id: 'jam-billies-bounce',
    name: "Billie's Bounce",
    subtitle: 'Jumbo Jazz · Jamendo',
    glyph: '🎷',
    tint: ['#4a3a2a', '#7a5a3a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-068493/04.mp3' },
    available: true,
  },
  {
    id: 'jam-butterfly',
    name: 'Butterfly',
    subtitle: 'Jumbo Jazz · Jamendo',
    glyph: '🎷',
    tint: ['#4a3a2a', '#7a5a3a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-068493/07.mp3' },
    available: true,
  },
  {
    id: 'jam-cantaloupe-island',
    name: 'Cantaloupe Island',
    subtitle: 'Jumbo Jazz · Jamendo',
    glyph: '🎷',
    tint: ['#4a3a2a', '#7a5a3a'],
    source: { kind: 'jamendo', url: 'https://archive.org/download/jamendo-068493/10.mp3' },
    available: true,
  },

  // ── Your coffee-shop lofi library (local files, public/audio/cozy/) ────
  {
    id: 'local-25minutes-study-timer-lofi-music-cute-bunny-timer-45min',
    name: 'Candlelight',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#5a3a1f', '#8a6b3f'],
    source: { kind: 'loop', url: '/audio/cozy/25minutes-study-timer---lofi-music---cute-bunny-timer-45min.mp3' },
    available: true,
  },
  {
    id: 'local-30-minute-timer-spring-blossom-30-min-timer-for-classroom',
    name: 'Slow Morning',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a2f1a', '#7a5533'],
    source: { kind: 'loop', url: '/audio/cozy/30-minute-timer-spring-blossom--30-min-timer-for-classroom.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-bebop-coffee-shop-517090',
    name: 'Gentle Current',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3f2a1c', '#6b4a30'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-bebop-coffee-shop-517090.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-blues-jazz-coffee-shop-552788',
    name: 'Meadow',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a3520', '#7a5f3a'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-blues-jazz-coffee-shop-552788.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-coffee-jazz-coffee-shop-music-564274',
    name: 'Mossy Path',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#55301a', '#8a5a35'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-coffee-jazz-coffee-shop-music-564274.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-coffee-shop-jazz-coffee-shop-music-564252',
    name: 'Cloud Nine',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3d2b18', '#6e5330'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-coffee-shop-jazz-coffee-shop-music-564252.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-coffee-shop-peaceful-afternoon-calm-573880',
    name: 'Porch Swing',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#5a3a1f', '#8a6b3f'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-coffee-shop-peaceful-afternoon-calm-573880.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-jazz-coffee-shop-music-556234',
    name: 'Fireside',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a2f1a', '#7a5533'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-jazz-coffee-shop-music-556234.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-jazz-coffee-shop-music-563580',
    name: 'Golden Hour',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3f2a1c', '#6b4a30'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-jazz-coffee-shop-music-563580.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-lofi-coffee-shop-568150',
    name: 'Quiet Pages',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a3520', '#7a5f3a'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-lofi-coffee-shop-568150.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-saxophone-jazz-coffee-shop-567545',
    name: 'Inkwell',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#55301a', '#8a5a35'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-saxophone-jazz-coffee-shop-567545.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-smooth-jazz-coffee-shop-568173',
    name: 'Cozy Corner',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3d2b18', '#6e5330'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-smooth-jazz-coffee-shop-568173.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-soul-jazz-coffee-shop-568168',
    name: 'Sunbeam',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#5a3a1f', '#8a6b3f'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-soul-jazz-coffee-shop-568168.mp3' },
    available: true,
  },
  {
    id: 'local-alex-morgan-stride-piano-coffee-shop-568148',
    name: 'Morning Dew',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a2f1a', '#7a5533'],
    source: { kind: 'loop', url: '/audio/cozy/alex-morgan-stride-piano-coffee-shop-568148.mp3' },
    available: true,
  },
  {
    id: 'local-andriih-cafe-coffee-shop-music-579806',
    name: 'Hazel Grove',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3f2a1c', '#6b4a30'],
    source: { kind: 'loop', url: '/audio/cozy/andriih-cafe-coffee-shop-music-579806.mp3' },
    available: true,
  },
  {
    id: 'local-andriih-coffee-coffee-morning-music-568236',
    name: 'Maple Breeze',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a3520', '#7a5f3a'],
    source: { kind: 'loop', url: '/audio/cozy/andriih-coffee-coffee-morning-music-568236.mp3' },
    available: true,
  },
  {
    id: 'local-andriih-cozy-cozy-coffee-music-568234',
    name: 'Bookmark',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#55301a', '#8a5a35'],
    source: { kind: 'loop', url: '/audio/cozy/andriih-cozy-cozy-coffee-music-568234.mp3' },
    available: true,
  },
  {
    id: 'local-andriih-french-coffee-jazz-567443',
    name: 'Honeyed',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3d2b18', '#6e5330'],
    source: { kind: 'loop', url: '/audio/cozy/andriih-french-coffee-jazz-567443.mp3' },
    available: true,
  },
  {
    id: 'local-apalonbeats-jazz-coffee-shop-music-560401',
    name: 'Brook',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#5a3a1f', '#8a6b3f'],
    source: { kind: 'loop', url: '/audio/cozy/apalonbeats-jazz-coffee-shop-music-560401.mp3' },
    available: true,
  },
  {
    id: 'local-bbibbilaaa-midnight-coffee-502447',
    name: 'Lavender Haze',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a2f1a', '#7a5533'],
    source: { kind: 'loop', url: '/audio/cozy/bbibbilaaa-midnight-coffee-502447.mp3' },
    available: true,
  },
  {
    id: 'local-celeronbeats-warm-sand-amp-coffee-chill-lofi-background-music-564345',
    name: 'Lamplit',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3f2a1c', '#6b4a30'],
    source: { kind: 'loop', url: '/audio/cozy/celeronbeats-warm-sand-amp-coffee-chill-lofi-background-music-564345.mp3' },
    available: true,
  },
  {
    id: 'local-cryptologymedia-coffee-shop-189585',
    name: 'Starlit',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a3520', '#7a5f3a'],
    source: { kind: 'loop', url: '/audio/cozy/cryptologymedia-coffee-shop-189585.mp3' },
    available: true,
  },
  {
    id: 'local-denis-pavlov-music-cozy-relax-jazz-podcast-coffee-ambiance-271621',
    name: 'Whisper',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#55301a', '#8a5a35'],
    source: { kind: 'loop', url: '/audio/cozy/denis-pavlov-music-cozy-relax-jazz-podcast-coffee-ambiance-271621.mp3' },
    available: true,
  },
  {
    id: 'local-denis-pavlov-music-podcast-jazz-music-168726',
    name: 'Rainy Window',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3d2b18', '#6e5330'],
    source: { kind: 'loop', url: '/audio/cozy/denis-pavlov-music-podcast-jazz-music-168726.mp3' },
    available: true,
  },
  {
    id: 'local-denis-pavlov-music-relaxing-jazz-podcast-coffee-shop-music-192283',
    name: 'Cinnamon Café',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#5a3a1f', '#8a6b3f'],
    source: { kind: 'loop', url: '/audio/cozy/denis-pavlov-music-relaxing-jazz-podcast-coffee-shop-music-192283.mp3' },
    available: true,
  },
  {
    id: 'local-elijah-k-coffee-293911',
    name: 'Tranquil',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a2f1a', '#7a5533'],
    source: { kind: 'loop', url: '/audio/cozy/elijah_k-coffee-293911.mp3' },
    available: true,
  },
  {
    id: 'local-gajju-m-christmas-eve-coffee-417646',
    name: 'Paper Lantern',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3f2a1c', '#6b4a30'],
    source: { kind: 'loop', url: '/audio/cozy/gajju_m-christmas-eve-coffee-417646.mp3' },
    available: true,
  },
  {
    id: 'local-juliush-coffee-brake-chill-out-music-1294',
    name: 'Daydream',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a3520', '#7a5f3a'],
    source: { kind: 'loop', url: '/audio/cozy/juliush-coffee-brake-chill-out-music-1294.mp3' },
    available: true,
  },
  {
    id: 'local-katzen-tupas-a-sip-of-coffee-to-relieve-stress-110620',
    name: 'Wind Chime',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#55301a', '#8a5a35'],
    source: { kind: 'loop', url: '/audio/cozy/katzen_tupas-a-sip-of-coffee-to-relieve-stress-110620.mp3' },
    available: true,
  },
  {
    id: 'local-lafrey-music-coffee-walk-516516',
    name: 'Velvet Dusk',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3d2b18', '#6e5330'],
    source: { kind: 'loop', url: '/audio/cozy/lafrey_music-coffee-walk-516516.mp3' },
    available: true,
  },
  {
    id: 'local-markmusicstudio-morning-coffee-555117',
    name: 'Moonlit Study',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#5a3a1f', '#8a6b3f'],
    source: { kind: 'loop', url: '/audio/cozy/markmusicstudio-morning-coffee-555117.mp3' },
    available: true,
  },
  {
    id: 'local-mondamusic-coffee-morning-coffee-shop-music-499186',
    name: 'Willow',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a2f1a', '#7a5533'],
    source: { kind: 'loop', url: '/audio/cozy/mondamusic-coffee-morning-coffee-shop-music-499186.mp3' },
    available: true,
  },
  {
    id: 'local-nastelbom-coffee-437346',
    name: 'Soft Focus',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3f2a1c', '#6b4a30'],
    source: { kind: 'loop', url: '/audio/cozy/nastelbom-coffee-437346.mp3' },
    available: true,
  },
  {
    id: 'local-onion-all-stars-like-black-coffee-137708',
    name: 'Hearth',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#4a3520', '#7a5f3a'],
    source: { kind: 'loop', url: '/audio/cozy/onion_all_stars-like-black-coffee-137708.mp3' },
    available: true,
  },
  {
    id: 'local-playlistsons-coffee-with-jazz-327479',
    name: 'Solstice',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#55301a', '#8a5a35'],
    source: { kind: 'loop', url: '/audio/cozy/playlistsons-coffee-with-jazz-327479.mp3' },
    available: true,
  },
  {
    id: 'local-the-mountain-coffee-lounge-lounge-music-508001',
    name: 'Pine Scent',
    subtitle: 'Coffee-shop lofi · your music',
    glyph: '🎧',
    tint: ['#3d2b18', '#6e5330'],
    source: { kind: 'loop', url: '/audio/cozy/the_mountain-coffee-lounge-lounge-music-508001.mp3' },
    available: true,
  },
  {
    id: 'local-where-sunlight-meets-stone',
    name: 'Amber Afternoon',
    subtitle: 'Your music · local file',
    glyph: '🎧',
    tint: ['#3f2a1c', '#6b4a30'],
    source: { kind: 'loop', url: '/audio/Where_Sunlight_Meets_Stone.mp3' },
    available: true,
  },
  {
    id: 'local-walk-beneath-the-ancient-arch',
    name: 'Fern & Fog',
    subtitle: 'Your music · local file',
    glyph: '🎧',
    tint: ['#4a3520', '#7a5f3a'],
    source: { kind: 'loop', url: '/audio/Walk_Beneath_the_Ancient_Arch.mp3' },
    available: true,
  },
  {
    id: 'local-sunday-morning-parchment',
    name: 'Warm Blanket',
    subtitle: 'Your music · local file',
    glyph: '🎧',
    tint: ['#55301a', '#8a5a35'],
    source: { kind: 'loop', url: '/audio/Sunday_Morning_Parchment.mp3' },
    available: true,
  },
]

export function getPreset(id: string | null | undefined): MusicPreset | undefined {
  return MUSIC_PRESETS.find((p) => p.id === id)
}

/** The default selection — first preset that can actually play today. */
export function firstAvailablePreset(): MusicPreset {
  return MUSIC_PRESETS.find((p) => p.available) ?? MUSIC_PRESETS[0]
}

/** Step to the next/previous AVAILABLE preset (wraps). Used by the ◀ ▶ controls.
 *  Returns the current id unchanged if fewer than one option is playable. */
export function adjacentAvailable(currentId: string | null, dir: 1 | -1): string {
  const playable = MUSIC_PRESETS.filter((p) => p.available)
  if (playable.length === 0) return currentId ?? ''
  const idx = playable.findIndex((p) => p.id === currentId)
  // If current isn't a playable preset, start from the first.
  const base = idx === -1 ? 0 : idx
  const nextIdx = (base + dir + playable.length) % playable.length
  return playable[nextIdx].id
}
